### ISSUE TITLE
Discrepancy between occurrence count in PBDB Explorer and Diversity end-point

### ISSUE THREAD

**Issue by jbryan6** [paleobiodb/bug_reports#15]
When using the PBDB Explorer and filtering on the Cenomanian stage, the system displays an occurrence count of 144395.  When using the diversity end-point, a value of 20216 is returned for number of occurrences.

API Link:
https://paleobiodb.org/data1.2/occs/diversity.json?interval=mesozoic&base_name=life

Screenshots:
![image](https://user-images.githubusercontent.com/32083532/31309274-9dfe55fa-ab51-11e7-90a0-30e17a03ba63.png)
![image](https://user-images.githubusercontent.com/32083532/31309275-a4e9f130-ab51-11e7-93c6-d9a3a041252a.png)
![image](https://user-images.githubusercontent.com/32083532/31309279-b774139e-ab51-11e7-8f83-276751097d4b.png)

**Comment by markuhen** [comment]
Moving this to the Navigator repo.
