### ISSUE TITLE
New Reference Form: Tip Sheet for Taxonomy field seems unrelated

### ISSUE THREAD

**Issue by jbryan6** [paleobiodb/bug_reports#18]
When creating a new reference there is a tip sheet link related to the taxonomy field.  The information presented seems to be related to classification of publications.   

https://paleobiodb.org/classic?action=displayPage&page=classification_quality

My expectation would be to see guidance related to the four elements presented in the Taxonomy drop-down so that I can select the correct value.   As a relative neophyte (the type of person who might most need a tip sheet), the information presented doesn't help me understand the four possible values.

![image](https://user-images.githubusercontent.com/32083532/31575519-d438d3d8-b0b6-11e7-976c-214be5008ee3.png)

**Comment by markuhen** [comment]
Moved to Classic repo.
